package com.Lbins.VegetableHm.dao.dao;

import android.database.sqlite.SQLiteDatabase;
import com.Lbins.VegetableHm.dao.RecordMsg;
import com.Lbins.VegetableHm.dao.ShoppingCart;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingCartDaoConfig;
    private final DaoConfig recordMsgDaoConfig;

    private final ShoppingCartDao shoppingCartDao;
    private final RecordMsgDao recordMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingCartDaoConfig = daoConfigMap.get(ShoppingCartDao.class).clone();
        shoppingCartDaoConfig.initIdentityScope(type);

        recordMsgDaoConfig = daoConfigMap.get(RecordMsgDao.class).clone();
        recordMsgDaoConfig.initIdentityScope(type);

        shoppingCartDao = new ShoppingCartDao(shoppingCartDaoConfig, this);
        recordMsgDao = new RecordMsgDao(recordMsgDaoConfig, this);

        registerDao(ShoppingCart.class, shoppingCartDao);
        registerDao(RecordMsg.class, recordMsgDao);
    }
    
    public void clear() {
        shoppingCartDaoConfig.getIdentityScope().clear();
        recordMsgDaoConfig.getIdentityScope().clear();
    }

    public ShoppingCartDao getShoppingCartDao() {
        return shoppingCartDao;
    }

    public RecordMsgDao getRecordMsgDao() {
        return recordMsgDao;
    }

}
