package com.Lbins.VegetableHm.dao;

import com.Lbins.VegetableHm.dao.dao.DaoSession;
import com.Lbins.VegetableHm.dao.dao.RecordMsgDao;
import de.greenrobot.dao.DaoException;

import java.io.Serializable;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table RECORD_MSG.
 */
public class RecordMsg implements Serializable {

    /**
     * Not-null value.
     */
    private String mm_msg_id;
    private String mm_emp_id;
    private String mm_msg_type;
    private String mm_msg_title;
    private String mm_msg_content;
    private String mm_msg_picurl;
    private String dateline;
    private String is_del;
    private String is_top;
    private String top_num;
    private String provinceid;
    private String cityid;
    private String countryid;
    private String area;
    private String accessToken;
    private String mm_emp_mobile;
    private String mm_emp_nickname;
    private String mm_emp_type;
    private String mm_emp_cover;
    private String mm_emp_company_type;
    private String mm_emp_company;
    private String mm_level_id;
    private String is_chengxin;
    private String is_miaomu;
    private String mm_level_num;
    private String is_read;
    private String mm_msg_video;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient RecordMsgDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RecordMsg() {
    }

    public RecordMsg(String mm_msg_id) {
        this.mm_msg_id = mm_msg_id;
    }

    public RecordMsg(String mm_msg_id, String mm_emp_id, String mm_msg_type, String mm_msg_title, String mm_msg_content, String mm_msg_picurl, String dateline, String is_del, String is_top, String top_num, String provinceid, String cityid, String countryid, String area, String accessToken, String mm_emp_mobile, String mm_emp_nickname, String mm_emp_type, String mm_emp_cover, String mm_emp_company_type, String mm_emp_company, String mm_level_id, String is_chengxin, String is_miaomu, String mm_level_num, String is_read, String mm_msg_video) {
        this.mm_msg_id = mm_msg_id;
        this.mm_emp_id = mm_emp_id;
        this.mm_msg_type = mm_msg_type;
        this.mm_msg_title = mm_msg_title;
        this.mm_msg_content = mm_msg_content;
        this.mm_msg_picurl = mm_msg_picurl;
        this.dateline = dateline;
        this.is_del = is_del;
        this.is_top = is_top;
        this.top_num = top_num;
        this.provinceid = provinceid;
        this.cityid = cityid;
        this.countryid = countryid;
        this.area = area;
        this.accessToken = accessToken;
        this.mm_emp_mobile = mm_emp_mobile;
        this.mm_emp_nickname = mm_emp_nickname;
        this.mm_emp_type = mm_emp_type;
        this.mm_emp_cover = mm_emp_cover;
        this.mm_emp_company_type = mm_emp_company_type;
        this.mm_emp_company = mm_emp_company;
        this.mm_level_id = mm_level_id;
        this.is_chengxin = is_chengxin;
        this.is_miaomu = is_miaomu;
        this.mm_level_num = mm_level_num;
        this.is_read = is_read;
        this.mm_msg_video = mm_msg_video;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRecordMsgDao() : null;
    }

    /**
     * Not-null value.
     */
    public String getMm_msg_id() {
        return mm_msg_id;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMm_msg_id(String mm_msg_id) {
        this.mm_msg_id = mm_msg_id;
    }

    public String getMm_emp_id() {
        return mm_emp_id;
    }

    public void setMm_emp_id(String mm_emp_id) {
        this.mm_emp_id = mm_emp_id;
    }

    public String getMm_msg_type() {
        return mm_msg_type;
    }

    public void setMm_msg_type(String mm_msg_type) {
        this.mm_msg_type = mm_msg_type;
    }

    public String getMm_msg_title() {
        return mm_msg_title;
    }

    public void setMm_msg_title(String mm_msg_title) {
        this.mm_msg_title = mm_msg_title;
    }

    public String getMm_msg_content() {
        return mm_msg_content;
    }

    public void setMm_msg_content(String mm_msg_content) {
        this.mm_msg_content = mm_msg_content;
    }

    public String getMm_msg_picurl() {
        return mm_msg_picurl;
    }

    public void setMm_msg_picurl(String mm_msg_picurl) {
        this.mm_msg_picurl = mm_msg_picurl;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getIs_del() {
        return is_del;
    }

    public void setIs_del(String is_del) {
        this.is_del = is_del;
    }

    public String getIs_top() {
        return is_top;
    }

    public void setIs_top(String is_top) {
        this.is_top = is_top;
    }

    public String getTop_num() {
        return top_num;
    }

    public void setTop_num(String top_num) {
        this.top_num = top_num;
    }

    public String getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getCityid() {
        return cityid;
    }

    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    public String getCountryid() {
        return countryid;
    }

    public void setCountryid(String countryid) {
        this.countryid = countryid;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getMm_emp_mobile() {
        return mm_emp_mobile;
    }

    public void setMm_emp_mobile(String mm_emp_mobile) {
        this.mm_emp_mobile = mm_emp_mobile;
    }

    public String getMm_emp_nickname() {
        return mm_emp_nickname;
    }

    public void setMm_emp_nickname(String mm_emp_nickname) {
        this.mm_emp_nickname = mm_emp_nickname;
    }

    public String getMm_emp_type() {
        return mm_emp_type;
    }

    public void setMm_emp_type(String mm_emp_type) {
        this.mm_emp_type = mm_emp_type;
    }

    public String getMm_emp_cover() {
        return mm_emp_cover;
    }

    public void setMm_emp_cover(String mm_emp_cover) {
        this.mm_emp_cover = mm_emp_cover;
    }

    public String getMm_emp_company_type() {
        return mm_emp_company_type;
    }

    public void setMm_emp_company_type(String mm_emp_company_type) {
        this.mm_emp_company_type = mm_emp_company_type;
    }

    public String getMm_emp_company() {
        return mm_emp_company;
    }

    public void setMm_emp_company(String mm_emp_company) {
        this.mm_emp_company = mm_emp_company;
    }

    public String getMm_level_id() {
        return mm_level_id;
    }

    public void setMm_level_id(String mm_level_id) {
        this.mm_level_id = mm_level_id;
    }

    public String getIs_chengxin() {
        return is_chengxin;
    }

    public void setIs_chengxin(String is_chengxin) {
        this.is_chengxin = is_chengxin;
    }

    public String getIs_miaomu() {
        return is_miaomu;
    }

    public void setIs_miaomu(String is_miaomu) {
        this.is_miaomu = is_miaomu;
    }

    public String getMm_level_num() {
        return mm_level_num;
    }

    public void setMm_level_num(String mm_level_num) {
        this.mm_level_num = mm_level_num;
    }

    public String getIs_read() {
        return is_read;
    }

    public void setIs_read(String is_read) {
        this.is_read = is_read;
    }

    public String getMm_msg_video() {
        return mm_msg_video;
    }

    public void setMm_msg_video(String mm_msg_video) {
        this.mm_msg_video = mm_msg_video;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
